export var decks = [

    {
      id: 1,
      category: 'choice',
      name: 'Editor Choice 1',
      items: 21,
      author: '@allen',
      code: 'CCS111',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 2,
      category: 'choice',
      name: 'Editor Choice 2',
      items: 34,
      author: '@watson',
      code: 'CCS111',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 3,
      category: 'choice',
      name: 'Editor Choice 3',
      items: 11,
      author: '@vhilly',
      code: 'CCS112',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 4,
      category: 'choice',
      name: 'Editor Choice 4',
      items: 76,
      author: '@christine',
      code: 'CCS112',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'yes',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },

    {
      id: 5,
      category: 'Business and Economics',
      name: 'Business 1',
      items: 35,
      author: '@angela',
      code: 'BSE111',
      course: 'Actuarial Sciences',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 6,
      category: 'Business and Economics',
      name: 'Business 2',
      items: 33,
      author: '@mak',
      code: 'BSE111',
      course: 'Petroleum Engineering',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 7,
      category: 'Business and Economics',
      name: 'Business 3',
      items: 99,
      author: '@deyb',
      code: 'BSE112',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 8,
      category: 'Business and Economics',
      name: 'Business 4',
      items: 96,
      author: '@grayedoutname',
      code: 'BSE112',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },

    {
      id: 9,
      category: 'Communications and Media',
      name: 'Communication 1',
      items: 65,
      author: '@yukonseeme',
      code: 'CMD111',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 10,
      category: 'Communications and Media',
      name: 'Communication 2',
      items: 12,
      author: '@risti',
      code: 'CMD111',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 11,
      category: 'Communications and Media',
      name: 'Communication 3',
      items: 69,
      author: '@ang4a',
      code: 'CMD112',
      course: 'Actuarial Sciences',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 12,
      category: 'Communications and Media',
      name: 'Communication 4',
      items: 99,
      author: '@makmak',
      code: 'CMD112',
      course: 'Petroleum Engineering',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 13,
      category: 'Computer Science',
      name: 'Computer Science 1',
      items: 34,
      author: '@allen',
      code: 'CCS111',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 14,
      category: 'Computer Science',
      name: 'Computer Science 2',
      items: 32,
      author: '@watson',
      code: 'CCS111',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 15,
      category: 'Computer Science',
      name: 'Computer Science 3',
      items: 20,
      author: '@vhilly',
      code: 'CCS112',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 16,
      category: 'Computer Science',
      name: 'Computer Science 4',
      items: 28,
      author: '@christine',
      code: 'CCS112',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'yes',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 17,
      category: 'Engineering',
      name: 'Engineering 1',
      items: 76,
      author: '@angela',
      code: 'ENG111',
      course: 'Actuarial Sciences',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 18,
      category: 'Engineering',
      name: 'Engineering 2',
      items: 72,
      author: '@mark',
      code: 'ENG111',
      course: 'Petroleum Engineering',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 19,
      category: 'Engineering',
      name: 'Engineering 3',
      items: 66,
      author: '@deyb',
      code: 'ENG112',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 20,
      category: 'Engineering',
      name: 'Engineering 4',
      items: 91,
      author: '@grayedoutname',
      code: 'ENG112',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 21,
      category: 'Health Sciences',
      name: 'Health Sciences 1',
      items: 14,
      author: '@yukonseeme',
      code: 'HLT111',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 22,
      category: 'Health Sciences',
      name: 'Health Sciences 2',
      items: 99,
      author: '@risti',
      code: 'HLT111',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 23,
      category: 'Health Sciences',
      name: 'Health Sciences 3',
      items: 63,
      author: '@ang4a',
      code: 'HLT112',
      course: 'Actuarial Sciences',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 24,
      category: 'Health Sciences',
      name: 'Health Sciences 4',
      items: 48,
      author: '@makmak',
      code: 'HLT112',
      course: 'Petroleum Engineering',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 25,
      category: 'Mathematics and Statistics',
      name: 'Mathematics 1',
      items: 77,
      author: '@allen',
      code: 'MTH111',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 26,
      category: 'Mathematics and Statistics',
      name: 'Mathematics 2',
      items: 94,
      author: '@watson',
      code: 'MTH111',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 27,
      category: 'Mathematics and Statistics',
      name: 'Mathematics 3',
      items: 27,
      author: '@vhilly',
      code: 'MTH112',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 28,
      category: 'Mathematics and Statistics',
      name: 'Mathematics 4',
      items: 26,
      author: '@christine',
      code: 'MTH112',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'yes',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 29,
      category: 'Natural Sciences',
      name: 'Natural Sciences 1',
      items: 6,
      author: '@angela',
      code: 'NTR111',
      course: 'Actuarial Sciences',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 30,
      category: 'Natural Sciences',
      name: 'Natural Sciences 2',
      items: 61,
      author: '@mark',
      code: 'NTR111',
      course: 'Petroleum Engineering',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 31,
      category: 'Natural Sciences',
      name: 'Natural Sciences 3',
      items: 98,
      author: '@deyb',
      code: 'NTR112',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 32,
      category: 'Natural Sciences',
      name: 'Natural Sciences 4',
      items: 39,
      author: '@grayedoutname',
      code: 'NTR112',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 33,
      category: 'Social Sciences',
      name: 'Social Sciences 1',
      items: 27,
      author: '@yukonseeme',
      code: 'SCL111',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 34,
      category: 'Social Sciences',
      name: 'Social Sciences 2',
      items: 42,
      author: '@risti',
      code: 'SCL111',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 35,
      category: 'Social Sciences',
      name: 'Social Sciences 3',
      items: 62,
      author: '@ang4a',
      code: 'SCL112',
      course: 'Actuarial Sciences',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 36,
      category: 'Social Sciences',
      name: 'Social Sciences 4',
      items: 17,
      author: '@makmak',
      code: 'SCL112',
      course: 'Petroleum Engineering',
      school: 'Adamson University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    
    {
      id: 37,
      category: 'Others',
      name: 'Others 1',
      items: 90,
      author: '@allen',
      code: 'MTH111',
      course: 'Computer Science',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 38,
      category: 'Others',
      name: 'Others 2',
      items: 15,
      author: '@watson',
      code: 'SCL112',
      course: 'Chemical Engineering',
      school: 'University of the East',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 39,
      category: 'Others',
      name: 'Others 3',
      items: 73,
      author: '@vhilly',
      code: 'ENG112',
      course: 'Physics',
      school: 'Far Eastern University',
      created: 'no',
      favorite: 'no',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    {
      id: 40,
      category: 'Others',
      name: 'Others 4',
      items: 16,
      author: '@christine',
      code: 'HLT112',
      course: 'Applied Mathematics',
      school: 'Far Eastern University',
      created: 'yes',
      favorite: 'yes',
      added: 'no',
      flashcards: [
        { frontContent: 'Front1', backContent: 'Back1' },
      ]
    },
    
  ]